Added drawing templates
tetrabiodistributed/tetrabiodistributed.github.io pull request #16
Opened 2021-02-24 17:31 UTC by darraghbr

Fixes https://github.com/tetrabiodistributed/papr-print-files/issues/70

2021-02-26 12:32 UTC, mechatroniks-git requested changes
Title block for Tetra A4 Drawing Template has A3 
![image](https://user-images.githubusercontent.com/57600622/109300348-3ed37f00-77eb-11eb-85a9-7156e36a56ec.png)

2021-02-26 12:45 UTC, darraghbr commented
Good catch, I have addressed in the new version.

Just for the sake of my own sanity, if anyone for some reason wants to export a drawing template from Fusion, you have to do it through the online Fusion team by downloading the template itself, it doesn't seem to let you do it from within Fusion itself.

2021-02-26 17:05 UTC, mechatroniks-git commented
A4 fixed in Fusion, so LTGM

2021-03-01 17:28 UTC, mechatroniks-git approved these changes

2021-03-01 17:43 UTC, merged